[package]
name = "delfi"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
log = "0.4.17"
serde = { version = "1.0", features = ["derive"] }

