[package]
name = "delfi"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "Conveniently writing data to csv-files"
repository = "https://github.com/skogseth/delfi"
keywords = ["csv", "data"]

[dependencies]
csv = "1.1"
log = "0.4.17"
serde = { version = "1.0", features = ["derive"] }

